### ISSUE TITLE
Version 0.2.6 broke my syntax highlighting.

### ISSUE THREAD

**Issue by pyvim** [atom-material/atom-material-syntax-dark#8]
Hello. After update to 0.2.6 all my Python code is grey without highlighting. Version 0.2.5 works normally.

I use [MagicPython](https://github.com/MagicStack/MagicPython) syntax highlighter instead default language-python. Maybe, it's reason of issue.

Could you check it?

**Comment by savbace** [comment]
the same issue for all file types on Atom 1.12.9

**Comment by nitinpaul** [comment]
I have the same issue. I'm on Ubuntu Linux, Atom 1.12.7

**Comment by Berieau** [comment]
Same issue here. Windows 10, Atom 1.12.9

**Comment by silvestreh** [comment]
My bad. The latest patch was intended for Atom 1.13 and I should've restricted. I'll see what I can do about it!

**Comment by silvestreh** [comment]
Yep, looks like if you guys don't want to update Atom to 1.13.0 you'll have to downgrade the syntax theme.

Fire up a terminal and write

```shell
apm install atom-material-syntax-dark@0.2.5
```

I just published another update that any Atom version before 1.13 will ignore.
